// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAhAZctDDv8a1dJEArXZEnHRrrZ-QT7is',
    appId: '1:107969526462:web:9c586e715631a30c577cef',
    messagingSenderId: '107969526462',
    projectId: 'exam2-16d57',
    authDomain: 'exam2-16d57.firebaseapp.com',
    storageBucket: 'exam2-16d57.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChje1j2YiziJbJnIcOfUL5kz1A5sKOqBY',
    appId: '1:107969526462:android:01e615f6859ee6dc577cef',
    messagingSenderId: '107969526462',
    projectId: 'exam2-16d57',
    storageBucket: 'exam2-16d57.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtBhwGayWn5IAYsVemk5_y2jSXS377Yxg',
    appId: '1:107969526462:ios:08b484b5c5716fc2577cef',
    messagingSenderId: '107969526462',
    projectId: 'exam2-16d57',
    storageBucket: 'exam2-16d57.firebasestorage.app',
    iosBundleId: 'com.example.exam2Advflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtBhwGayWn5IAYsVemk5_y2jSXS377Yxg',
    appId: '1:107969526462:ios:08b484b5c5716fc2577cef',
    messagingSenderId: '107969526462',
    projectId: 'exam2-16d57',
    storageBucket: 'exam2-16d57.firebasestorage.app',
    iosBundleId: 'com.example.exam2Advflutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAhAZctDDv8a1dJEArXZEnHRrrZ-QT7is',
    appId: '1:107969526462:web:2a0aeeede824ca4d577cef',
    messagingSenderId: '107969526462',
    projectId: 'exam2-16d57',
    authDomain: 'exam2-16d57.firebaseapp.com',
    storageBucket: 'exam2-16d57.firebasestorage.app',
  );
}
